# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 12.x
          - 14.x
        architecture:
          - x64
          # FIXME: GitHub does not offer arm64 runners at the moment.
          #
          # We can enalbe arm64 builds in the future when GitHub offers arm64 runners or we decide
          # to set up a self-hosted runner on arm64.
          # See also https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners
          # and https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners
          # - arm64 # Jetson Devices

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} - ${{ matrix.architecture }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        architecture: ${{ matrix.architecture }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npm run lint
